### ISSUE TITLE
image fail right after start

### ISSUE THREAD

**Issue by truekoi** [broxus/ton-kafka-producer#4]
Hi Team!
Once solved an issue w/an image preparation I've run into another problem, have a look - 

> INFO ton_kafka_producer: version="0.2.1"
> INFO ton_kafka_producer: initializing producer
> INFO ton_kafka_producer::config: using public ip ip_address=<IP_HERE>
> WARN ton_indexer::config::node_keys: failed to read ADNL keys, generating new
> WARN ton_kafka_producer::blocks_handler::kafka_producer: flushing kafka producer
> Error: Failed to create engine
> 
> Caused by:
>  0: Failed to start node
>  1: Failed to apply migrations
>  2: No suitable migration found for version [2, 0, 8]
> exited with code 1

Can you point me in the right direction (even if this direction is to avoid of using docker at all) 
Thanks in advance

**Comment by Rexagon** [comment]
**If you are trying to run it using the db from `ever-node`:**
This project is based on [`ton-indexer`](https://github.com/broxus/ton-indexer/) which is an alternative implementation of the light node. It is not interchangeable with validator node.

**If you are updating the node:**
It seems like the existing DB version is incompatible, try to resync the node.

> I am very sorry for this decision (breaking changes in the db). But it was the only way to move to a more reliable structure (and improved GC, it can now run in the background without affecting everything else).

---

NOTE:
If the node was stopped (or you need to start from the past) more than ~1 day ago, it is better to find the required masterchain block seqno and update the config:
```
scan_type:
  kind: FromNetwork
  node_config:
    ...
    start_from: 123123 <---
```

**Comment by truekoi** [comment]
Started w/empty '/var/db' solved my issue, thanks for such a fast response,  you're really doing great job  guys!
